function subsubpage1
clear
clc

%% 创建主界面
hf = figure('Name','测量数据基本处理',...
    'NumberTitle','off',...
    'Position',[200,200,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;

%% 等精度测量数据误差分析
axes('Units','pixels',...
    'Position',[0,70,350,400],...
    'CreateFcn',@plot1);
uicontrol(hf,...
    'Style','text',...
    'String','等精度测量数据误差分析',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','subsubpage1_1',...
    'Position',[0,30,300,25]);

%% 不等精度测量数据误差分析
axes('Units','pixels',...
    'Position',[300,70,400,400],...
    'CreateFcn',@plot2);
uicontrol(hf,...
    'Style','text',...
    'String','不等精度测量数据误差分析',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','subsubpage1_2',...
    'Position',[310,30,300,25]);

%% 返回
uicontrol(hf,...
    'Style','text',...
    'String','返回',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','page_exit',...
    'Position',[620,30,90,25]);

function plot1(~,~)
[I,~,alpha] = imread('image/photo_1_1.png');
h = imshow(I);
set(h,'AlphaData',alpha);

function plot2(~,~)
[I,~,alpha] = imread('image/photo_1_2.png');
h = imshow(I);
set(h,'AlphaData',alpha);
