function subsubpage4
clear
clc

%% 创建主界面
hf = figure('Name','最小二乘法处理',...
    'NumberTitle','off',...
    'Position',[200,200,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;

%% 等精度测量线性参数最小二乘法处理
axes('Units','pixels',...
    'Position',[0,70,350,400],...
    'CreateFcn',@plot1);
uicontrol(hf,...
    'Style','text',...
    'String','等精度测量线性参数最小二乘法处理',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','subsubpage4_1',...
    'Position',[0,100,400,25]);
uicontrol(hf,...
    'Style','text',...
    'String','图一：最小二乘法处理数据',...
    'FontSize',10,...
    'BackgroundColor','white',...
    'Position',[0,385,350,25]);


%% 不等精度测量线性参数最小二乘法处理
axes('Units','pixels',...
    'Position',[361,70,350,400],...
    'CreateFcn',@plot2);
uicontrol(hf,...
    'Style','text',...
    'String','不等精度测量线性参数最小二乘法处理',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','subsubpage4_2',...
    'Position',[210,60,400,25]);
uicontrol(hf,...
    'Style','text',...
    'String','图二：最小二乘法计算玉米粒数',...
    'FontSize',10,...
    'BackgroundColor','white',...
    'Position',[361,385,350,25]);

%% 返回
uicontrol(hf,...
    'Style','text',...
    'String','返回',...
    'FontSize',16,...
    'FontWeight','bold',...
    'enable','inactive',...
    'ButtonDownFcn','page_exit',...
    'Position',[360,20,350,25]);

function plot1(~,~)
imshow('image/photo_4_1.jpg');

function plot2(~,~)
imshow('image/photo_4_2.jpg');
