function subsubpage4_1
clear
clc

%% 创建主界面
hf = figure('Name','等精度测量线性参数最小二乘法处理',...
    'NumberTitle','off',...
    'Position',[200,200,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;