function subsubpage1
clear
clc

%% 创建主界面
s = get(0,'ScreenSize');% 获取计算机屏幕分辨率
x = s(3)*0.15;
y = s(4)*0.26;
hf = figure('Name','测量数据基本处理',...
    'NumberTitle','off',...
    'Position',[x,y,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;

% 静态文本框
t = 1:3;
t_string = {'等精度测量数据误差分析','不等精度测量数据误差分析','返回'};
t_position = [0,30,300,25;310,30,300,25;620,30,90,25;];
for i = 1:length(t)
    t(i) = uicontrol(hf,...
        'Style','text',...
        'String',t_string{i},...
        'FontSize',16,...
        'FontWeight','bold',...
        'enable','inactive',...
        'Units','pixels',...
        'Position',t_position(i,:));
end
set(t(1),'ButtonDownFcn','subsubpage1_1');
set(t(2),'ButtonDownFcn','subsubpage1_2');
set(t(3),'ButtonDownFcn','page_exit');

axes('Units','pixels',...
    'Position',[0,70,350,400],...
    'CreateFcn',@plot1);
axes('Units','pixels',...
    'Position',[300,70,400,400],...
    'CreateFcn',@plot2);

function plot1(cbo,handles)
[I,c,alpha] = imread('image/photo_1_1.png');
h = imshow(I);
set(h,'AlphaData',alpha);

function plot2(cbo,handles)
[I,c,alpha] = imread('image/photo_1_2.png');
h = imshow(I);
set(h,'AlphaData',alpha);