function subsubpage3
clear
clc

%% 创建主界面
hf = figure('Name','测量不确定度',...
    'NumberTitle','off',...
    'Position',[200,200,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;