function subsubpage4
clear
clc

%% 创建主界面
s = get(0,'ScreenSize');% 获取计算机屏幕分辨率
x = s(3)*0.15;
y = s(4)*0.26;
hf = figure('Name','最小二乘法处理',...
    'NumberTitle','off',...
    'Position',[x,y,710,450],...
    'MenuBar','none',...
    'Color','White',...
    'Resize','off');

% 更改界面左上角图标
icon;

% 静态文本框
t = 1:3;
t_string = {'等精度测量线性参数最小二乘法处理','不等精度测量线性参数最小二乘法处理','返回'};
t_position = [0,100,400,25;210,60,400,25;360,20,350,25;];
for i = 1:length(t)
    t(i) = uicontrol(hf,...
        'Style','text',...
        'String',t_string(i),...
        'FontSize',16,...
        'FontWeight','bold',...
        'enable','inactive',...
        'Units','pixels',...
        'Position',t_position(i,:));
end
set(t(1),'ButtonDownFcn','subsubpage4_1');
set(t(2),'ButtonDownFcn','subsubpage4_2');
set(t(3),'ButtonDownFcn','page_exit');

t1 = 1:2;
t1_string = {'图一：最小二乘法处理数据','图二：最小二乘法计算玉米粒数'};
t1_position = [0,385,350,25;361,385,350,25;];
for i = 1:length(t1)
    t1(i) = uicontrol(hf,...
        'Style','text',...
        'String',t1_string(i),...
        'FontSize',10,...
        'BackgroundColor','white',...
        'Units','pixels',...
        'Position',t1_position(i,:));
end

axes('Units','pixels',...
    'Position',[0,70,350,400],...
    'CreateFcn','imshow(''image/photo_4_1.jpg'');');
axes('Units','pixels',...
    'Position',[361,70,350,400],...
    'CreateFcn','imshow(''image/photo_4_2.jpg'');');